-- MySQL Script generated by MySQL Workbench
-- Sun Oct  8 16:48:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Pinatas_Fantasy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pinatas_Fantasy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pinatas_Fantasy` ;
USE `Pinatas_Fantasy` ;

-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`usuario_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`usuario_cliente` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`usuario_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`usuario_admin` (
  `idusuario_admin` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Info_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Info_cliente` (
  `id_info_cliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido_P` VARCHAR(45) NULL,
  `Apellido_M` VARCHAR(45) NULL,
  `Telefono` VARCHAR(10) NULL,
  `usuario_cliente_idusuarios` INT NOT NULL,
  PRIMARY KEY (`id_info_cliente`),
  CONSTRAINT `fk_Info_cliente_usuario_cliente1`
    FOREIGN KEY (`usuario_cliente_idusuarios`)
    REFERENCES `Pinatas_Fantasy`.`usuario_cliente` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Tipos_de_piñatas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Tipos_de_piñatas` (
  `idTipos_de_piñatas` INT NOT NULL,
  `Tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipos_de_piñatas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Festividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Festividades` (
  `idFestividades` INT NOT NULL,
  `Nombre_festividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idFestividades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Piñata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Piñata` (
  `idPiñatas` INT NOT NULL,
  `Nombre_pinata` VARCHAR(45) NULL,
  `Tipos_de_piñatas_idTipos_de_piñatas` INT NOT NULL,
  `Festividades_idFestividades` INT NOT NULL,
  `Precio` VARCHAR(45) NULL,
  `Imagen` VARCHAR(200) NULL,
  PRIMARY KEY (`idPiñatas`),
  INDEX `fk_Piñatas_Tipos_de_piñatas1_idx` (`Tipos_de_piñatas_idTipos_de_piñatas` ASC) VISIBLE,
  INDEX `fk_Piñata_Festividades1_idx` (`Festividades_idFestividades` ASC) VISIBLE,
  CONSTRAINT `fk_Piñatas_Tipos_de_piñatas1`
    FOREIGN KEY (`Tipos_de_piñatas_idTipos_de_piñatas`)
    REFERENCES `Pinatas_Fantasy`.`Tipos_de_piñatas` (`idTipos_de_piñatas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Piñata_Festividades1`
    FOREIGN KEY (`Festividades_idFestividades`)
    REFERENCES `Pinatas_Fantasy`.`Festividades` (`idFestividades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Piñatas_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Piñatas_detalles` (
  `idPiñatas_detalles` INT NOT NULL,
  `Tamaño` VARCHAR(45) NULL,
  `Colores` VARCHAR(45) NULL,
  `Tiempo estimado` VARCHAR(45) NULL,
  `Stock` VARCHAR(45) NULL,
  `Piñata_idPiñatas` INT NOT NULL,
  PRIMARY KEY (`idPiñatas_detalles`),
  INDEX `fk_Piñatas_detalles_Piñata1_idx` (`Piñata_idPiñatas` ASC) VISIBLE,
  CONSTRAINT `fk_Piñatas_detalles_Piñata1`
    FOREIGN KEY (`Piñata_idPiñatas`)
    REFERENCES `Pinatas_Fantasy`.`Piñata` (`idPiñatas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Contacto` (
  `idContacto` INT NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  `Telefono` VARCHAR(30) NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`pedido` (
  `idpedido` INT NOT NULL,
  `Estatus` VARCHAR(45) NULL,
  `Fecha_estimada` VARCHAR(45) NULL,
  `Piñata_idPiñatas` INT NOT NULL,
  `usuario_cliente_idusuarios` INT NOT NULL,
  `Contacto_idContacto` INT NOT NULL,
  PRIMARY KEY (`idpedido`),
  INDEX `fk_pedido_Piñata1_idx` (`Piñata_idPiñatas` ASC) VISIBLE,
  INDEX `fk_pedido_usuario_cliente1_idx` (`usuario_cliente_idusuarios` ASC) VISIBLE,
  INDEX `fk_pedido_Contacto1_idx` (`Contacto_idContacto` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_Piñata1`
    FOREIGN KEY (`Piñata_idPiñatas`)
    REFERENCES `Pinatas_Fantasy`.`Piñata` (`idPiñatas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_usuario_cliente1`
    FOREIGN KEY (`usuario_cliente_idusuarios`)
    REFERENCES `Pinatas_Fantasy`.`usuario_cliente` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_Contacto1`
    FOREIGN KEY (`Contacto_idContacto`)
    REFERENCES `Pinatas_Fantasy`.`Contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Proceso del pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Proceso del pedido` (
  `ID` INT NOT NULL,
  `pedido_idpedido` INT NOT NULL,
  `Anticipo` VARCHAR(45) NOT NULL,
  `Pago Final` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Proceso del pedido_pedido1`
    FOREIGN KEY (`pedido_idpedido`)
    REFERENCES `Pinatas_Fantasy`.`pedido` (`idpedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Inventario` (
  `idInventario` INT NOT NULL,
  `Existencia` INT NULL,
  `Vendido` INT NULL,
  `Apartado` INT NULL,
  `Total` INT NULL,
  `Piñatas_detalles_idPiñatas_detalles` INT NOT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `fk_Inventario_Piñatas_detalles1_idx` (`Piñatas_detalles_idPiñatas_detalles` ASC) VISIBLE,
  CONSTRAINT `fk_Inventario_Piñatas_detalles1`
    FOREIGN KEY (`Piñatas_detalles_idPiñatas_detalles`)
    REFERENCES `Pinatas_Fantasy`.`Piñatas_detalles` (`idPiñatas_detalles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pinatas_Fantasy`.`Token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pinatas_Fantasy`.`Token` (
  `idToken` INT NOT NULL AUTO_INCREMENT,
  `Token` VARCHAR(70) NULL,
  `usuario` VARCHAR(45) NULL,
  `Fecha_de_exp` DATETIME NULL,
  PRIMARY KEY (`idToken`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
